sudo: required
dist: trusty

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_install:
        - chmod +x mvnw

    - language: node_js
      node_js: stable
      before_install:
        - cd ./src/angular/angular-meixner/
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      install:
        - run mvn clean compile || true
        - npm install
      script:
        - npm run build
