sudo: required
dist: trusty

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_install:
        - chmod +x mvnw
      script:
        - ./mvnw test -B -q
      before_script:
        - cd ./spring/

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./angular/
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - npm run build