sudo: required
dist: trusty

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      env:
        - DOCKER_COMPOSE_VERSION=3
      script:
        - mvn test
      before_install:
        - chmod +x mvnw
        - sudo apt-get update
        - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
        - docker-compose --version
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - docker-compose pull
        - docker-compose build
        - docker-compose start

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./src/angular/angular-meixner/
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - npm run build