version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: meixner-sql
    volumes:
      - meixner-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "database_user"
      MYSQL_PASSWORD: "password"
volumes:
  meixner-mysql:
    external: true
